### PR TITLE
Shield

### PR DESCRIPTION
**Pull request by beaesguerra**

### CODE REVIEW

**Comment by ExtraGravity** [comment]
The shield is not being drawn on the correct spot
screenshot from 2015-12-26 22 23 32

This is an issue drawing scale, it looks fine when run with just `python3 main.py` but I run with `python3 main.py 2` and that causes problems.

**Comment by ExtraGravity** [comment]
Also can we make it have a blue outline?

**Comment by beaesguerra** [comment]
Fixed!

**Comment by ExtraGravity** [comment]
Very cool, I was originally thinking a solid blue outline but this effect looks cool as well. Also cyan is much better than blue :)

**Pull request merged**
