### PR TITLE
Score and ui

### PR DESCRIPTION
**Pull request by ExtraGravity**

### CODE REVIEW

**Comment by ExtraGravity** [comment]
I added a game over screen. @beaesguerra @bseto

**Comment by beaesguerra** [comment]
Do you think players would want to know what the high score is while playing the game or when they lost the game? Or nah?

**Comment by beaesguerra** [comment]
Also, please make the size of the text in the targeting terminal the same as the weapon selection text. I think it'll make it a lot easier on the eyes

**Comment by ExtraGravity** [comment]
Ok I'll increase the size

**Comment by beaesguerra** [comment]
Should the high score be displayed in the game over screen? So you can see if you beat the high score when you're done?

**Comment by ExtraGravity** [comment]
I guess it could, not hard to change. But I think it's unnecessary information while playing.

**Comment by ExtraGravity** [comment]
screenshot from 2015-12-27 16 12 30

**Pull request merged**
