### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ExtraGravity**

### CODE REVIEW

**Comment by bseto** [comment]
Merge conflicts. I will review again, and before accepting pull request, you will need to squash some commits.

Search up git rebase -i and squash these all later (After I review first)

**Comment by gordon-cheung** [comment]
Game crashes when typing "fire" after a target is locked on using homing missiles. Please fix and I'll review again ;D

**Comment by gordon-cheung** [comment]
Looks good, I noticed the enemies do not fire back in this branch. Should you merge master and push up on branch, or would it be ok to merge pull request as it is now?

**Comment by gordon-cheung** [comment]
Jokes there are now merge conflicts.

**Comment by ExtraGravity** [comment]
Fixed the bug of enemies not shooting.

**Comment by gordon-cheung** [comment]
Is main menu suppose to be working for this branch? python3 main.py has an error. Otherwise it looks good to merge.

**Comment by ExtraGravity** [comment]
fixed

**Pull request merged**
