### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ExtraGravity**
I've **set up testing using googletest**. The source has been statically compiled for this project so no one needs to install google test themselves, if you don't know what this means it's not really that important but you can ask me. The compiled library being used is `libgtest.a` in the `test` folder.

I've written **one sample test, hitbox_test.cpp**, you can look up further google test examples online but that file is one simple test for the `hitbox` class, testing the `is_overlapping` function, you should be able to build off that. **Try writing your own test** and get used to it, we'll be writing a lot of tests :)

I've created a compile script for us that will compile the source for the game, compile the tests, then run the tests. **Use this make-all script for compilation from now on** so that you can see any failures of tests right after you compile. 

I've also adjusted the Makefiles to be a bit smarter. `OBJS = $(wildcard src/*.cpp)` will compile all the `.cpp` files in the `src` folder. This way we don't need to edit the Makefile every time we add a new class.

I've also **cleaned up the LINK_FLAGS by removing some libraries** that we don't need. We should adjust our install script accordingly sometime but that's not really urgent at all. 

I also added code to make sure **all the source files compile (like collision_detector.h), but they're not tested**.

### CODE REVIEW

**Comment by bseto** [comment]
About the OBJS= parameter. We can leave it with your edit for now, however, this will not work in the future as we want to move to a incremental build: http://stackoverflow.com/questions/8663626/make-and-incremental-builds. This will allow us to specify -j4 or -jN, N being the number of threads to compile with.

**Comment by bseto** [comment]
Also, I am getting an error when running ./make-all

```
./make-all 
g++ src/game_object.cpp src/delay.cpp src/collision_detector.cpp src/graphics_handler.cpp src/universe.cpp src/missile.cpp src/hitbox.cpp src/missile_launcher.cpp src/main.cpp src/projectile.cpp  -Ilib -Iinclude `sdl2-config --cflags` `sdl2-config --libs` -lSDL2_image -lSDL2_ttf -pthread -w -g -std=c++0x -o TerminalFighter
make: Entering directory '/home/byron/Documents/TerminalFighter/test'
g++ -isystem gtest_include -I../src -Ilib src/my_test.cpp src/hitbox_test.cpp ../src/game_object.cpp ../src/delay.cpp ../src/collision_detector.cpp ../src/graphics_handler.cpp ../src/universe.cpp ../src/missile.cpp ../src/hitbox.cpp ../src/missile_launcher.cpp ../src/projectile.cpp `sdl2-config --cflags` `sdl2-config --libs` -lSDL2_image -lSDL2_ttf -pthread -w -g -std=c++0x -pthread libgtest.a -o run-tests
/tmp/ccOIWXBs.o: In function `testing::AssertionResult testing::internal::CmpHelperEQFailure<bool, bool>(char const*, char const*, bool const&, bool const&)':
/home/byron/Documents/TerminalFighter/test/gtest_include/gtest/gtest.h:1382: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 1
make: Leaving directory '/home/byron/Documents/TerminalFighter/test'
./make-all: line 3: ./test/run-tests: No such file or directory
```

Do i have to install something else? Getting a linker "Undefined Reference" error.

**Comment by ExtraGravity** [comment]
Not sure, you might have to compile google test yourself?

**Comment by ExtraGravity** [comment]
I'm having a hard time figuring out why yours isn't working @bseto  because it's working with travis which usually has more issues.

**Comment by ExtraGravity** [comment]
What we can try is you compiling the library yourself. We have to to opt for this if it's due to incompatible libraries between our machines.

To do this, clone google test from their repo https://github.com/google/googletest

Then compile using this command, replace ${GTEST_DIR} with whatever works for you. Note the repo comes with googletest and googlemock, you only need to compile google test.
`g++ -isystem googletest/include -Igoogletest 
    -pthread -c googletest/src/gtest-all.cc`

Then compress the library definitions into an archive file
`ar -rv libgtest.a gtest-all.o`

You now have your own compiled function definitions for google test. Replace the libgtest.a I've pushed up with your own then try compiling the tests.

**Comment by ExtraGravity** [comment]
This is indeed the case. I will add the .a file to the ignore and give instructions for compiling googletest ourself. I will reopen this pull request when it is ready.

**Comment by ExtraGravity** [comment]
What's that last commit, merge branch 'testing' into testing

**Comment by bseto** [comment]
I pulled to merge your commits to my local commits before pushing them up.

**Pull request merged**
